In [1]:
pip install nnfs


Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np 
from nnfs.datasets import spiral_data

In [3]:
# ouput of a single neuron 
inputs = [1.1,2.1,3.4]
weights = [1,-1,2]
bias = 3 

output = inputs[0]*weights[0] + inputs[1]*weights[1] +inputs[2]*weights[2] + bias

output

8.8

In [4]:
# Coding a layer 
# 3 inputs from the previous layer
# 2 outputs 
# dimW = 2x3
inputs = [1.1,2.1,3.4]
weights1 = [1,-1,2]
bias1 = 3 
output1 = inputs[0]*weights1[0] + inputs[1]*weights1[1] +inputs[2]*weights1[2] + bias1

inputs = [1.1,2.1,3.4]
weights2 = [1.2,5,2.5]
bias2 = 8 
output2 = inputs[0]*weights2[0] + inputs[1]*weights2[1] +inputs[2]*weights2[2] + bias2

print([output1 , output2])



[8.8, 28.32]


In [5]:
# The weights matrix 
#Matrix notation
W  = [[1,-1,2],
     [1.2,5,2.5],
     [4,.05,-2.05]]
B = [3,8,-5]

In [6]:
W = np.array(W)
W.shape

(3, 3)

In [7]:
B = np.array(B)
inputs = np.array(inputs )
B.shape, inputs.shape

((3,), (3,))

In [8]:
output = np.matmul(W,inputs) + B
output

array([ 8.8  , 28.32 , -7.465])

In [9]:
# Multiple layer of nueron
# multiple inputs

inputs = [[0.1,7.1,.4],
         [1.8,-2.1,.14],
         [2.9,2.6,3.6],
         [4.1,0.9,3.97],
         [6.1,-2.1,2.4]]
inputs = np.transpose(inputs)

B = [[3,8,-5],
    [3,8,-5],
    [3,8,-5],
    [3,8,-5],
    [3,8,-5]]
B = np.transpose(B)


output = np.matmul(W,inputs) + B
output

array([[-3.2000e+00,  7.1800e+00,  1.0500e+01,  1.4140e+01,  1.6000e+01],
       [ 4.4620e+01,  1.0000e-02,  3.3480e+01,  2.7345e+01,  1.0820e+01],
       [-5.0650e+00,  1.8080e+00, -6.5000e-01,  3.3065e+00,  1.4375e+01]])

In [10]:
# Another way of doing 
inputs = [[0.1,7.1,.4],
         [1.8,-2.1,.14],
         [2.9,2.6,3.6],
         [4.1,0.9,3.97],
         [6.1,-2.1,2.4]]
W_T = np.transpose(W)

B = [[3,8,-5],
    [3,8,-5],
    [3,8,-5],
    [3,8,-5],
    [3,8,-5]]



output = np.matmul(inputs,W_T) + B
output
#Outputs here are represented horizontally 

array([[-3.2000e+00,  4.4620e+01, -5.0650e+00],
       [ 7.1800e+00,  1.0000e-02,  1.8080e+00],
       [ 1.0500e+01,  3.3480e+01, -6.5000e-01],
       [ 1.4140e+01,  2.7345e+01,  3.3065e+00],
       [ 1.6000e+01,  1.0820e+01,  1.4375e+01]])

In [11]:
#2 layers 
X = [[0.1,7.1,.4],
         [1.8,-2.1,.14],
         [2.9,2.6,3.6],
         [4.1,0.9,3.97],
         [6.1,-2.1,2.4]]
#Hidden layer 1
#weights of layer 1 

W_1 = [[1,-1,2],
     [1.2,5,2.5],
     [4,.05,-2.05]]

W_T_1 = np.transpose(W)

#Bias for layer 1 

B_1 = [[3,8,-5],
    [3,8,-5],
    [3,8,-5],
    [3,8,-5],
    [3,8,-5]]

layer1_output = np.matmul(X,W_T_1) + B_1

#Now Layer 1 output becomes input for the next layer 

#Hidden layer 2

#weights of layer 2

W_2 = [[0.4,1,-2],
     [1.7,-2.5,3.5],
     [-2.4,.5,-2.05]]
W_T_2 = np.transpose(W_2)

#Bias of layer 2 

B_2 = [1.5,4,-5]


layer2_output = np.matmul(layer1_output,W_T_2) + B_2

layer1_output,layer2_output

(array([[-3.2000e+00,  4.4620e+01, -5.0650e+00],
        [ 7.1800e+00,  1.0000e-02,  1.8080e+00],
        [ 1.0500e+01,  3.3480e+01, -6.5000e-01],
        [ 1.4140e+01,  2.7345e+01,  3.3065e+00],
        [ 1.6000e+01,  1.0820e+01,  1.4375e+01]]),
 array([[  54.97    , -130.7175  ,   35.37325 ],
        [   0.766   ,   22.509   ,  -25.9334  ],
        [  40.48    ,  -64.125   ,  -12.1275  ],
        [  27.888   ,  -28.75175 ,  -32.041825],
        [ -10.03    ,   54.4625  ,  -67.45875 ]]))

In [12]:
# Creating a class of layers

class Layer_dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights = np.random.randn(n_inputs,n_neurons)
        self.biases = np.random.rand(1,n_neurons)
    def forward(self,inputs):
        self.output = np.matmul(inputs,self.weights) + self.biases


In [13]:
#Activation function 
#sigmoid
class Activation_sig:
    def forward(self,inputs):
        self.output = 1/(1 + np.exp(-inputs))

#classifier

class Classifier:
    def forward(self,inputs):        
        self.output = np.around(inputs)

In [14]:
#creating data
X,y = spiral_data(100,2)

In [15]:
X.shape

(200, 2)

In [16]:
layer1 = Layer_dense(2,5)
activation1 = Activation_sig()

#Creating output for the first layer
layer1.forward(X)
layer1.output

#Applying activation function and  output for 2nd layer
activation1.forward(layer1.output)
activation1.output

layer2 = Layer_dense(5,4)
activation2 = Activation_sig()

#Creating output for the first layer
layer2.forward(activation1.output)
(layer2.output)

#Applying activation function and  output for 2nd layer
activation2.forward(layer2.output)
((activation2.output))

#Final layer

layer_final = Layer_dense(4,1)
layer_final.forward(activation2.output)

#squishing data between 0 and 1 

activation3 = Activation_sig()
activation3.forward(layer_final.output)

#classifying for the final output 

Classify  = Classifier()
Classify.forward(activation3.output)
y_pred = Classify.output


In [17]:
## Loss function (logistic regression) 

class cost:
    def loss(self,y_predicted,y_actual):
        self.output = np.mean(-y_actual*np.log(y_predicted)-(1-y_actual)*np.log(1 - y_predicted))
    

In [18]:
Cost = cost()
Cost.loss(y_pred,y)
Cost.output

C:\Users\Yesh\AppData\Local\Temp\ipykernel_26336\1715291824.py:5: RuntimeWarning: divide by zero encountered in log
  self.output = np.mean(-y_actual*np.log(y_predicted)-(1-y_actual)*np.log(1 - y_predicted))
C:\Users\Yesh\AppData\Local\Temp\ipykernel_26336\1715291824.py:5: RuntimeWarning: invalid value encountered in multiply
  self.output = np.mean(-y_actual*np.log(y_predicted)-(1-y_actual)*np.log(1 - y_predicted))


nan

### BACKPROPOGATION 